hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user start foot-server")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("systemctl --user start mako")
	hl.exec_cmd("systemctl --user start hyprpaper")
	hl.exec_cmd("/home/lunya/.cargo/bin/ashell")
	hl.exec_cmd("fcitx5")
	hl.exec_cmd("steam -silent")
end)
